from prompts import get_prompt
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
import os
import pandas as pd
import time
from datetime import datetime
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.output_parsers import StrOutputParser
from utilities import llm_output_clean, validate_sql
from vector_store import store_successful_query, retrieve_similar_queries, check_duplication

load_dotenv()
gemini_key=os.getenv('GEMINI_API_KEY')

root_path = os.getcwd()

conversation_history = []

logging_dict = {
    'user_question': None,
    'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'generated_sql': None,
    'execution_time_ms': 0,
    'retrieved_count': 0,
    'retrieval_time_ms': 0,
    'rag_used': False,
    'status': None,
    'error': None
}

def logging(log_dict):
    log_path = os.path.join(root_path, 'data/logs')
    log_file = os.path.join(log_path, 'sql_generation_logs.csv')
    
    os.makedirs(log_path, exist_ok=True)

    logging_df = pd.DataFrame([log_dict])
    if os.path.exists(log_file):
        logging_df.to_csv(log_file, mode='a', header=False, index=False)
    else:
        logging_df.to_csv(log_file, mode='w', header=True, index=False)

def add_to_conversation(question, sql, rows_returned):
    """Add a turn to conversation history."""
    turn = {
        "turn": len(conversation_history) + 1,
         "question": question,
         "sql": sql,
         "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
         "rows_returned": rows_returned
    }

    conversation_history.append(turn)

    if len(conversation_history) > 3:
        conversation_history.pop(0)

def get_conversation_context():
    """Format conversation history for prompt."""
    if not conversation_history:
        return ""
    
    context = "\n\nPrevious conversation:\n"
    for turn in conversation_history:
        context += f"\nTurn {turn['turn']}:\n"
        context += f"User: \"{turn['question']}\"\n"
        context += f"SQL: {turn['sql']}\n"

    context += "\nNow answer the current question using context if needed.\n"
    return context

def clear_conversation():
    """Clear conversation memory."""
    global conversation_history
    conversation_history = []
    print("Conversation cleared")

def generate_sql(user_question):
    """
        Function that takes a user question and returns SQL using llm gemini-2.5-flash
        Parameters: user_question (string)
        Returns: tuple (sql_query string, retrieved_examples list)
    """
    
    prompt = get_prompt()
    logging_dict['user_question'] = user_question

    # Retrieve similar queries ONCE
    retrieved_examples = []
    try:
        start_time = time.time()
        retrieved_examples = retrieve_similar_queries(user_question)
        logging_dict['retrieval_time_ms'] = round((time.time() - start_time) * 1000, 2)
    except Exception as e:
        print(f"⚠️ Warning: Retrieval failed ({e}), using static examples only")
        retrieved_examples = []

    retrieved_examples_count = len(retrieved_examples)

    if retrieved_examples_count > 0:
        logging_dict['rag_used'] = True

    logging_dict['retrieved_count'] = retrieved_examples_count

    try:
        conversation_context = get_conversation_context()
        print("🤖 Fetching from LLM...")
        start_time = time.time()

        llm = ChatGoogleGenerativeAI(
            model="gemini-2.5-flash",
            temperature=0,  
            max_tokens=2000,
            timeout=None,
            max_retries=2,
            convert_system_message_to_human=True
        )

        output_parser = StrOutputParser()

        chain = prompt | llm | output_parser

        sql = chain.invoke({"question": user_question, "retrieved_examples": retrieved_examples, "conversation_context": conversation_context})
        sql = llm_output_clean(sql)

        end_time = time.time()

        logging_dict['generated_sql'] = sql
        logging_dict['execution_time_ms'] = round((end_time - start_time) * 1000, 2)

        return sql, retrieved_examples 

    except Exception as e:
        print(f"❌ Error generating SQL: {e}")
        logging_dict['status'] = 'failed'
        logging_dict['error'] = str(e)
        logging(logging_dict)
        return None, retrieved_examples

def ask_database(user_question):
    """
        Function that connects database so it can execute the queries generated by llm
        Parameters: user_question (string)
        Returns: results (list of dictionaries or pandas DataFrame)
    """

    try:
        sql, retrieved_examples = generate_sql(user_question)
    except Exception as e:
        error_str = str(e)
        if "429" in error_str or "quota" in error_str.lower() or "rate limit" in error_str.lower():
            print("🚫 API Rate Limit Exceeded!")
            print("Gemini API quota is exhausted. Please wait and try again later.")
            print(f"Tip: Check your quota at https://aistudio.google.com")
            logging_dict['status'] = 'failed'
            logging_dict['error'] = "Rate limit exceeded"
            logging(logging_dict)
            return None
        else:
            raise e

    if sql == None:
        print("❌ Could not generate SQL. Your question might be ambiguous.")
        print("Please provide more details about which tables or columns you're interested in.")
        logging_dict['status'] = 'failed'
        logging_dict['error'] = "Empty SQL"
        logging(logging_dict)
        return None
    else:
        is_valid, error_msg = validate_sql(sql)
        if not is_valid:
            print(f"🚫 Validation Error: {error_msg}")
            logging_dict['status'] = 'failed'
            logging_dict['error'] = error_msg
            logging(logging_dict)
            return None
        else: 
            dbname=os.getenv('DB_NAME')
            user=os.getenv('DB_USER')
            password=os.getenv('DB_PASS')
            host=os.getenv('DB_HOST')
            port=os.getenv('DB_PORT')

            engine = create_engine(
                f"postgresql://{user}:{password}@{host}:{port}/{dbname}",
                connect_args={
                    'options': '-c statement_timeout=5000' 
                }
            )
            try: 
                with engine.connect() as conn:
                    start_time = time.time()
                    conn.execute(text("SET statement_timeout = '5s'"))
                    df = pd.read_sql(text(sql), conn)
                    execution_time = round((time.time() - start_time) * 1000, 2)
                    rows_returned = len(df)
                    
                    if not df.empty:
                        print("\n✅ Query Results:")
                        print(df.to_string(index=False))
                        print(f"\n📊 Returned {rows_returned} row(s)")
                    else:
                        print("⚠️ Query executed successfully but returned no results.")
                    
                    add_to_conversation(user_question, sql, rows_returned)
                    
                    logging_dict['status'] = 'success'
                    logging_dict['error'] = None
                    logging(logging_dict)

                    if check_duplication(sql, retrieved_examples):
                        store_successful_query(user_question, sql, rows_returned, execution_time)
                        print("💾 Query stored in ChromaDB")

                    return df
                    
            except Exception as e:
                if "canceling statement due to statement timeout" in str(e):
                    print("⏱️ Query timeout: Query took longer than 5 seconds.")
                    print("💡 Try narrowing your search with date filters or LIMIT.")
                else:
                    print(f"❌ SQL Execution Error: {e}")
                    print(f"\n📝 Generated SQL was:\n{sql}")
                
                logging_dict['status'] = 'failed'
                logging_dict['error'] = str(e)
                logging(logging_dict)
                return None

# Test examples
if __name__ == "__main__":
    print("Welcome to QueryMate - Ask Questions (type 'exit' to quit)")

    while True:
        user_question = input('\n Your question: ')
        if user_question.lower() in ['exit', 'quit', 'q']:
            print("👋 Goodbye!")
            break
        
        if user_question.lower() in ['clear', 'reset', 'new']:
            clear_conversation()
            continue
        
        if user_question.strip():
            ask_database(user_question)

        else:
            print("Please enter a question")

    
# Test questions:
# "How many customers are there?"
# "Show me 10 customers from Sao Paulo"
# "What are the top 5 product categories?"
# "How many orders in January 2017?"
# "What was total revenue in 2017?"
# "Show average order value by state"
# "Show me sales" (intentionally ambiguous)
# "Show orders from 2025" (no data exists)
# "How many users are there?" (wrong table name - should be customers)
# "Which customers left 5-star reviews and spent over 500?"