from prompts import get_prompt
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
import os
import pandas as pd
import time
from datetime import datetime
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.output_parsers import StrOutputParser
from utilities import llm_output_clean, validate_sql
from vector_store import store_successful_query

load_dotenv()
gemini_key=os.getenv('GEMINI_API_KEY')

root_path = os.getcwd()

logging_dict = {
    'user_question': None,
    'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'generated_sql': None,
    'execution_time_ms': 0,
    'status': None,
    'error': None
}

def logging(log_dict):
    log_path = os.path.join(root_path, 'data/logs')
    log_file = os.path.join(log_path, 'sql_generation_logs.csv')
    
    os.makedirs(log_path, exist_ok=True)

    logging_df = pd.DataFrame([log_dict])
    if os.path.exists(log_file):
        logging_df.to_csv(log_file, mode='a', header=False, index=False)
    else:
        logging_df.to_csv(log_file, mode='w', header=True, index=False)

def generate_sql(user_question):
    """
        Function that takes a user question and returns SQL using llm gemini-2.5-flash
        Parameters: user_question (string)
        Returns: sql_query (string)
    """
    
    prompt = get_prompt()
    logging_dict['user_question'] = user_question

    try:
        print("Fetching from LLM...")
        start_time = time.time()

        llm = ChatGoogleGenerativeAI(
            model="gemini-2.5-flash-lite",
            temperature=1.0,  
            max_tokens=500,
            timeout=None,
            max_retries=2,
            convert_system_message_to_human=True
        )

        output_parser = StrOutputParser()

        chain = prompt | llm | output_parser

        sql = chain.invoke({"question": user_question})
        sql = llm_output_clean(sql)

        end_time = time.time()

        logging_dict['generated_sql'] = sql
        logging_dict['execution_time_ms'] = round((end_time - start_time) * 1000, 2)

    except Exception as e:
        print(f"Error generating SQL: {e}")
        return None
    
    return sql

def ask_database(user_question):
    """
        Function that connects database so it can execute the queries generated by llm
        Parameters: user_question (string)
        Returns: results (list of dictionaries or pandas DataFrame)
    """

    sql = generate_sql(user_question)

    if sql == None:
        print("❌ Could not generate SQL. Your question might be ambiguous.")
        print("Please provide more details about which tables or columns you're interested in.")
        logging_dict['status'] = 'failed'
        logging_dict['error'] = "Empty SQL"
        logging(logging_dict)
        return None
    else:
        is_valid, error_msg = validate_sql(sql)
        if not is_valid:
            print(f"🚫 Validation Error: {error_msg}")
            logging_dict['status'] = 'failed'
            logging_dict['error'] = "Invalid SQL"
            logging(logging_dict)
            return None
        else: 
            dbname=os.getenv('DB_NAME')
            user=os.getenv('DB_USER')
            password=os.getenv('DB_PASS')
            host=os.getenv('DB_HOST')
            port=os.getenv('DB_PORT')

            engine = create_engine(
                f"postgresql://{user}:{password}@{host}:{port}/{dbname}",
                connect_args={
                    'options': '-c statement_timeout=5000' 
                }
            )
            try: 
                with engine.connect() as conn:
                    start_time = time.time()
                    conn.execute(text("SET statement_timeout = '5s'"))
                    df = pd.read_sql(text(sql), conn)
                    execution_time = time.time() - start_time
                    rows_returned = len(df)
                    if not df.empty:
                        print("\nQuery Results:")
                        print(df.to_string(index=False))
                        print(f"\nReturned {rows_returned} row(s)")
                    else:
                        print("Query executed successfully but returned no results.")
                    logging_dict['status'] = 'success'
                    logging_dict['error'] = "None"
                    logging(logging_dict)
                    store_successful_query(user_question, sql, rows_returned, execution_time)
                    return True
            except Exception as e:
                if "canceling statement due to statement timeout" in str(e):
                    print("⏱️ Query timeout: Query took longer than 5 seconds.")
                    print("Try narrowing your search with date filters or LIMIT.")
                else:
                    print(f"SQL Execution Error: {e}")
                    print(f"\nGenerated SQL was:\n{sql}")
                logging_dict['status'] = 'failed'
                logging_dict['error'] = f"Error: {e}"
                logging(logging_dict)
            
user_questions = 'Show average order value by state'
ask_database(user_questions)

    
# How many users are there?
# Which customers left 5-star reviews and spent more than 500 total